# Run tests

name: CI

on:
  # This will run when any branch or tag is pushed
  workflow_dispatch:
  push:
    branches:
      - feature/markdown_diff

jobs:

  check:
    # These checks only need to be done once, not for every python version we
    # support
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Use the current version of Python
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install mdformat-gfm mdformat-frontmatter mdformat-footnote
      - name: validate readme with mdformat
        id: validate_readme
        run: mdformat --check README.md
        continue-on-error: true
      - name: check mdformat result
        run: |
          mdformat_result = "${{ steps.validate_readme.outcome}}"
          echo $mdformat_result
          if [ ${{ steps.validate_readme.outcome }} == "failure" ]; then
              mkdir -p /tmp/pypiserver
              cp README.md /tmp/pypiserver
              echo "README.md is not formatted correctly. Please run 'mdformat README.md' and commit the result."
              mdformat /tmp/pypiserver/README.md
              diff -u README.md /tmp/pypiserver/README.md
              exit 1
          fi
