# Run tests

name: CI

on:
  # This will run when any branch or tag is pushed
  push:
    branches:
      - "master"
    tags:
      - "v**"
  # Allowing to run on fork and other pull requests
  workflow_dispatch:

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade setuptools
          pip install tox==3.27.*
      - name: Run tests
        run: tox -e py

  check:
    # These checks only need to be done once, not for every python version we
    # support
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Use the current version of Python
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install -r "requirements/dev.pip"
          pip install types-pkg_resources # one of mypy required stubs
      - name: Check types
        # individual mypy files for now, until we get the rest
        # of the project typechecking
        run: >-
          mypy
          docker/test_docker.py
          pypiserver/config.py 
          tests/test_init.py
      - name: Check formatting
        run: black --diff --check .
      - name: Validate README
        run: mdformat --check README.md

