# Run tests

name: CI

on:
  # This will run when any branch or tag is pushed
  workflow_dispatch:
  push:
    branches:
      - feature/markdown_diff

jobs:

  check:
    # These checks only need to be done once, not for every python version we
    # support
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Use the current version of Python
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install -r "requirements/dev.pip"
      - name: validate readme with mdformat
        id: validate_readme
        run: mdformat --check README.md
        continue-on-error: true
      - name: check mdformat result
        run: |
          # echo result of previous step to make sure it is run
          echo "${{ steps.validate_readme.outcome}}"
          echo "${{ steps.validate_readme.outputs.result }}"
          mkdir -p /tmp/pypiserver
          cp README.md /tmp/pypiserver
          echo "README.md is not formatted correctly. Please run 'mdformat --in-place README.md' and commit the result."
          mdformat --in-place /tmp/pypiserver/README.md
          diff -u README.md /tmp/pypiserver/README.md
          exit 1
